/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package slider;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author marcelinol
 */
public class TheSlider extends javax.swing.JPanel implements java.beans.Customizer {
    
    
    /** Requisitos do trabalho **/
    protected String imageFolder;
    protected int interval = 1;
    protected boolean controlVisible = true;
    private File currentFile;
    /** --------------------- **/
    
    private Object bean;
    private java.util.Timer timer;
    private File [] listOfFiles;
    int contador = 0;
    
    /**
     * Creates new customizer TheSlider
     */
    public TheSlider() {
        imageFolder = "images";
        listOfFiles = new File(imageFolder).listFiles();
        initComponents();
        btnPlay.setEnabled(false);
        jPanel2.setVisible(controlVisible);
        play();
    }
    
    public void play() {
        TheSlider componente = this;
        timer = new java.util.Timer();
        timer.schedule(new java.util.TimerTask() {
            public void run() {
                componente.incrementaContador();
                currentFile = listOfFiles[componente.getContador()];
                componente.imageLabel.repaint();
            }
        },
        interval*1000, /* tempo para 1a execução */
        interval*1000 /* intervalo de repetição */
        );
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }
    
    public int getContador() {
        return this.contador;
    }
    
    public void incrementaContador() {
        if(contador == (this.listOfFiles.length - 1)) {
            this.contador = 0;
        } else {
            this.contador++;
        }
    }

    public void decrementaContador() {
        if(this.contador == 0) {
            this.contador = this.listOfFiles.length - 1;
        } else {
            this.contador--;
        }
    }

    /**
     * Get the value of imageFolder
     *
     * @return the value of imageFolder
     */
    public String getImageFolder() {
        return imageFolder;
    }

    /**
     * Set the value of imageFolder
     *
     * @param imageFolder new value of imageFolder
     */
    public void setImageFolder(String imageFolder) {
        this.imageFolder = imageFolder;
    }

    /**
     * Get the value of interval
     *
     * @return the value of interval
     */
    public int getInterval() {
        
        return interval;
    }

    /**
     * Set the value of interval
     *
     * @param interval new value of interval
     */
    public void setInterval(int interval) {
        this.interval = interval;
    }
    

    /**
     * Get the value of controlVisible
     *
     * @return the value of controlVisible
     */
    public boolean isControlVisible() {
        return controlVisible;
    }

    /**
     * Set the value of controlVisible
     *
     * @param controlVisible new value of controlVisible
     */
    public void setControlVisible(boolean controlVisible) {
        this.controlVisible = controlVisible;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 =  new javax.swing.JLabel() {
            @Override
            public void paint(Graphics g) {
                try {
                    BufferedImage img = ImageIO.read(currentFile);
                    g.drawImage(img, 0, 0, this.getWidth(), this.getHeight(), null);
                } catch (IOException ioe) { ioe.printStackTrace(); }
            }
        };
        imageLabel =  new javax.swing.JLabel() {
             @Override
             public void paint(Graphics g) {
                 try {
                 BufferedImage img = ImageIO.read(currentFile);
                 g.drawImage(img, 0, 0, this.getWidth(), this.getHeight(), null);
                 } catch (IOException ioe) { ioe.printStackTrace(); }
             }
         };
        jPanel2 = new javax.swing.JPanel();
        previousImageButton = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();
        nextImageButton = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);

        imageLabel.setText("imageLabel");
        imageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageLabelMouseClicked(evt);
            }
        });

        previousImageButton.setText("Imagem anterior");
        previousImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousImageButtonActionPerformed(evt);
            }
        });

        btnPlay.setText("Play");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        nextImageButton.setText("Próxima imagem");
        nextImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextImageButtonActionPerformed(evt);
            }
        });

        btnStop.setText("Stop");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(previousImageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nextImageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(previousImageButton)
                    .addComponent(btnStop)
                    .addComponent(btnPlay)
                    .addComponent(nextImageButton))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        this.timer.cancel();
        btnPlay.setEnabled(true);
        btnStop.setEnabled(false);
    }//GEN-LAST:event_btnStopActionPerformed

    private void nextImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextImageButtonActionPerformed
        this.incrementaContador();
        this.currentFile = listOfFiles[this.contador];
        imageLabel.repaint();
    }//GEN-LAST:event_nextImageButtonActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        play();
        btnStop.setEnabled(true);
        btnPlay.setEnabled(false);
    }//GEN-LAST:event_btnPlayActionPerformed

    private void previousImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousImageButtonActionPerformed
        this.decrementaContador();
        this.currentFile = listOfFiles[this.contador];
        imageLabel.repaint();
    }//GEN-LAST:event_previousImageButtonActionPerformed

    private void imageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabelMouseClicked
//        if(evt.getClickCount() == 2) {
            // ABRIR IMAGEM MAXIMIZADA
            // jPanel1.setVisible(true); // nao ta funcionando
//        }
    }//GEN-LAST:event_imageLabelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton nextImageButton;
    private javax.swing.JButton previousImageButton;
    // End of variables declaration//GEN-END:variables
}
